### ISSUE TITLE
Sticky headers pass touch events to the list item below

### ISSUE THREAD

**Issue by tererecool** [Doist/RecyclerViewExtensions#20]
Hello, it is supposed that the list goes below the sticky header, when the backgorund of the header is transparent you can see this happening, the problem is, while the backgound is opaque, you touch the header and list item currently below of the header gets selected.

**Comment by tererecool** [comment]
Ok, this happens if you set clickable and focusable to false in the layout for the header, setting them to true solves the problem.

**Comment by goncalossilva** [comment]
Indeed, it's just a view on top of the others. By default if a view isn't focusable it'll let touches pass below it.
