### ISSUE TITLE
Second header showing over first one

### ISSUE THREAD

**Issue by mobilekosmos** [Doist/RecyclerViewExtensions#21]
The library works well on vertical layout but in landscape mode I could detect that eventually the second header would show over the first one, don't know the cause of this. I tried changing the used layouts many times, but it did not make any difference.
My list shows the first header, then there are 5 lis items where 4 are visible on Nexus 6, I scroll down until I see the second header and all works as expected. Then I go completely up again, first header still showing up correctly, now I scroll down 1mm and the second header is shown above the first one. I inspected it with the layout inspector and I can see that both header are on top, one over the other.
I then changed the lib by [this one](https://github.com/bgogetap/StickyHeaders) and with it it works as expected.

**Comment by goncalossilva** [comment]
Sticky headers have been through a few revisions since this report. Hopefully the issue is fixed! If not, could you please reopen with reproduction steps? Thanks.
