### ISSUE TITLE
Convert to Kotlin

### ISSUE THREAD

**Issue by nguyentando** [Doist/RecyclerViewExtensions#26]
I wonder if there's a need to convert the whole codebase into Kotlin. 
If yes, I'm willing to contribute.

**Comment by alkairsenness** [comment]
Yes, it would be great to have it completely converted to Kotlin.

**Comment by goncalossilva** [comment]
Thanks for offering to help! The way I see it, users of this library should not have to pull in kotlin-stdlib to use it. They might not necessarily be using Kotlin. Considering the library is mostly feature-complete and stable, I'm also skeptical of the benefits it would bring this late in the development cycle.

We love Kotlin and use it thoroughly in our own apps, but I would not introduce it here at least until there is some major new iteration. :smile:
