### ISSUE TITLE
StickyHeaders not working with ConcatAdapter

### ISSUE THREAD

**Issue by RIS2000** [Doist/RecyclerViewExtensions#44]
will be any fixes ?

ps: thanks for a great extensions!

**Comment by goncalossilva** [comment]
We don't use `ConcatAdapter`, so it's tough to allocate time to add support for it! We'd accept a PR.

**Comment by XXQAQ** [comment]
I'm fixed it
And it can support ConcatAdapter nested ConcatAdapter

**Comment by XXQAQ** [comment]
I'm fixed it. Please see https://github.com/XXQAQ/StickyFor

**Comment by goncalossilva** [comment]
We'd gladly accept a PR!
